# Configuration du scanner de vols

# Aéroports d'origine (codes IATA)
origins:
  - CDG  # Paris Charles de Gaulle
  - ORY  # Paris Orly
  - BVA  # Paris Beauvais
  - BOS  # Boston Logan

# Destinations à scanner (codes IATA)
# Vous pouvez ajouter/modifier cette liste selon vos besoins
destinations:
  # Liste exhaustive de ~1413 destinations dans le monde
  - AAE
  - AAL
  - ABE
  - ABJ
  - ABQ
  - ABT
  - ABV
  - ACC
  - ACE
  - ACT
  - ADA
  - ADB
  - ADD
  - ADL
  - ADZ
  - AEP
  - AES
  - AEY
  - AGA
  - AGP
  - AGT
  - AHB
  - AIT
  - AIU
  - AJA
  - AKL
  - AKX
  - ALA
  - ALB
  - ALC
  - ALG
  - ALP
  - AMA
  - AMD
  - AMM
  - AMS
  - ANF
  - ANP
  - ANR
  - ANU
  - AOI
  - APW
  - AQJ
  - AQP
  - ARK
  - ARN
  - ASD
  - ASJ
  - ASM
  - ASR
  - ASU
  - ASW
  - ATH
  - ATL
  - AUH
  - AUS
  - AVL
  - AXA
  - AXM
  - AXT
  - AYK
  - AYP
  - AYT
  - AZS
  - BAH
  - BAL
  - BAQ
  - BCN
  - BDL
  - BDP
  - BDS
  - BEG
  - BEL
  - BEN
  - BER
  - BES
  - BEY
  - BFJ
  - BFN
  - BFS
  - BGF
  - BGI
  - BGO
  - BGW
  - BGY
  - BHH
  - BHM
  - BHR
  - BHX
  - BIN
  - BIO
  - BIQ
  - BIR
  - BIS
  - BJL
  - BJU
  - BJV
  - BKI
  - BKK
  - BKO
  - BLA
  - BLJ
  - BLL
  - BLQ
  - BLR
  - BMI
  - BNA
  - BNE
  - BOD
  - BOG
  - BOH
  - BOI
  - BOJ
  - BOM
  - BOO
  - BOS
  - BRC
  - BRE
  - BRI
  - BRN
  - BRO
  - BRQ
  - BRS
  - BRU
  - BSB
  - BSL
  - BSR
  - BTR
  - BTS
  - BTV
  - BUD
  - BUF
  - BUH
  - BUR
  - BWA
  - BWI
  - BXH
  - BZE
  - BZG
  - BZO
  - BZV
  - CAG
  - CAI
  - CAK
  - CAN
  - CBS
  - CCP
  - CCS
  - CCU
  - CDG
  - CEB
  - CFE
  - CFN
  - CFU
  - CGK
  - CGN
  - CGP
  - CHA
  - CHC
  - CHM
  - CHS
  - CIA
  - CID
  - CIO
  - CIT
  - CIX
  - CJA
  - CJU
  - CLE
  - CLJ
  - CLO
  - CLT
  - CLY
  - CMB
  - CMH
  - CMI
  - CMN
  - CND
  - CNF
  - CNS
  - CNX
  - COK
  - COO
  - COR
  - CPH
  - CPT
  - CRA
  - CRI
  - CRL
  - CRP
  - CRV
  - CSK
  - CSX
  - CTA
  - CTG
  - CTM
  - CTS
  - CTU
  - CUE
  - CUK
  - CUN
  - CUU
  - CUZ
  - CVG
  - CVM
  - CWB
  - CWL
  - CXB
  - CYB
  - CZE
  - CZM
  - DAB
  - DAC
  - DAD
  - DAL
  - DAM
  - DAR
  - DBV
  - DCA
  - DEB
  - DEC
  - DEL
  - DEN
  - DFW
  - DGA
  - DGO
  - DHA
  - DHI
  - DIJ
  - DIR
  - DJE
  - DKR
  - DLA
  - DLC
  - DLE
  - DLH
  - DLM
  - DMB
  - DMK
  - DMM
  - DOH
  - DOP
  - DPS
  - DRS
  - DRW
  - DSM
  - DSS
  - DTM
  - DTW
  - DUB
  - DUD
  - DUR
  - DUS
  - DVO
  - DWC
  - DXB
  - DZN
  - EBB
  - EBL
  - ECN
  - ECP
  - EDI
  - EDO
  - EGS
  - EIN
  - EIS
  - ELH
  - ELP
  - ELQ
  - ELS
  - EMD
  - ENU
  - ERC
  - ERF
  - ERI
  - ESB
  - ESM
  - ETZ
  - EWR
  - EXT
  - EYW
  - EZE
  - FAH
  - FAO
  - FAR
  - FAT
  - FBD
  - FCO
  - FDH
  - FEZ
  - FGI
  - FIH
  - FKB
  - FKS
  - FLL
  - FLN
  - FLR
  - FMO
  - FMY
  - FNC
  - FNI
  - FNT
  - FOC
  - FOG
  - FOR
  - FPO
  - FRA
  - FRU
  - FSC
  - FSM
  - FUE
  - FUK
  - FWA
  - GAU
  - GCM
  - GDE
  - GDL
  - GDN
  - GDT
  - GEA
  - GEG
  - GEO
  - GGG
  - GGT
  - GHA
  - GIG
  - GIS
  - GIZ
  - GKH
  - GLA
  - GMZ
  - GND
  - GNV
  - GNY
  - GOA
  - GOM
  - GOT
  - GPT
  - GRB
  - GRG
  - GRJ
  - GRQ
  - GRR
  - GRU
  - GRZ
  - GSO
  - GUW
  - GVA
  - GWD
  - GYE
  - GYR
  - GZT
  - HAJ
  - HAM
  - HAN
  - HAS
  - HAV
  - HBA
  - HDY
  - HEA
  - HEH
  - HEL
  - HER
  - HGH
  - HHN
  - HIJ
  - HKD
  - HKG
  - HKK
  - HKT
  - HLZ
  - HMO
  - HND
  - HNL
  - HOF
  - HOU
  - HPH
  - HPN
  - HRE
  - HRG
  - HRI
  - HRL
  - HSG
  - HSV
  - HTY
  - HUX
  - HVB
  - HYD
  - IAD
  - IAH
  - IAS
  - IBR
  - IBZ
  - ICI
  - ICN
  - ICT
  - IEG
  - IFJ
  - IGR
  - IKI
  - ILO
  - ILP
  - ILZ
  - IND
  - INI
  - INN
  - IQQ
  - IQT
  - ISB
  - ISC
  - ISP
  - IST
  - ISU
  - IVC
  - IXB
  - IXC
  - IXE
  - IXJ
  - IXL
  - IXM
  - IXR
  - IXS
  - IXU
  - IXY
  - IXZ
  - IZM
  - IZO
  - JAA
  - JAF
  - JAI
  - JAX
  - JBQ
  - JDH
  - JED
  - JFK
  - JGA
  - JGB
  - JIJ
  - JKR
  - JKT
  - JLR
  - JMK
  - JMO
  - JNB
  - JOE
  - JRH
  - JRO
  - JSA
  - JSH
  - JSK
  - JSR
  - JTR
  - JUB
  - JUL
  - JUM
  - JUV
  - KAN
  - KBL
  - KBV
  - KCH
  - KCT
  - KCZ
  - KDH
  - KDU
  - KDV
  - KEF
  - KEY
  - KGF
  - KGL
  - KGS
  - KHH
  - KHI
  - KIN
  - KIR
  - KIS
  - KIX
  - KKE
  - KKJ
  - KLU
  - KMG
  - KMI
  - KMJ
  - KMX
  - KNQ
  - KOA
  - KOJ
  - KOK
  - KOS
  - KOV
  - KRK
  - KRT
  - KSC
  - KSY
  - KTM
  - KTW
  - KUA
  - KUH
  - KUL
  - KUN
  - KUO
  - KVA
  - KWI
  - KWJ
  - KYA
  - KYP
  - KZK
  - KZO
  - LAD
  - LAG
  - LAN
  - LAP
  - LAS
  - LAX
  - LBB
  - LBS
  - LBU
  - LBV
  - LCA
  - LCJ
  - LCY
  - LDH
  - LDN
  - LEI
  - LEJ
  - LEQ
  - LEV
  - LFR
  - LFW
  - LGA
  - LGB
  - LGG
  - LGK
  - LGQ
  - LGW
  - LHE
  - LHR
  - LHW
  - LIF
  - LIG
  - LIH
  - LIL
  - LIM
  - LIN
  - LIS
  - LIT
  - LJU
  - LMM
  - LNZ
  - LOH
  - LON
  - LOS
  - LPA
  - LPL
  - LPP
  - LPQ
  - LPT
  - LQN
  - LRD
  - LRM
  - LSC
  - LSH
  - LST
  - LTN
  - LTO
  - LUA
  - LUN
  - LUX
  - LXR
  - LYB
  - LYG
  - LYS
  - MAA
  - MAC
  - MAD
  - MAF
  - MAN
  - MAO
  - MAR
  - MBA
  - MBJ
  - MBX
  - MCI
  - MCO
  - MCT
  - MDC
  - MDE
  - MDL
  - MDZ
  - MEC
  - MED
  - MEE
  - MEL
  - MEM
  - MEX
  - MEY
  - MFE
  - MFM
  - MGS
  - MGZ
  - MHH
  - MHQ
  - MHX
  - MIA
  - MID
  - MIL
  - MIR
  - MJD
  - MJT
  - MKE
  - MKY
  - MLI
  - MLM
  - MLN
  - MLU
  - MLX
  - MMB
  - MMJ
  - MMX
  - MMZ
  - MNF
  - MNL
  - MOB
  - MON
  - MPL
  - MRS
  - MSN
  - MSP
  - MST
  - MSY
  - MTH
  - MTY
  - MUK
  - MUN
  - MUS
  - MUX
  - MWZ
  - MXL
  - MXP
  - MXS
  - MYJ
  - MYT
  - MYY
  - MZE
  - MZT
  - MZV
  - NAN
  - NAP
  - NAS
  - NAT
  - NAV
  - NBO
  - NCE
  - NCL
  - NDJ
  - NGB
  - NGI
  - NGO
  - NGS
  - NGX
  - NIM
  - NKG
  - NLD
  - NLK
  - NOC
  - NOU
  - NPE
  - NPL
  - NQY
  - NRT
  - NSN
  - NST
  - NTE
  - NTL
  - NTT
  - NUE
  - NYU
  - OAI
  - OAK
  - OAX
  - OAZ
  - OBO
  - OGG
  - OHD
  - OIT
  - OKA
  - OKC
  - OKD
  - OKE
  - OKI
  - OKJ
  - OMA
  - OMR
  - ONJ
  - ONQ
  - ONT
  - OOL
  - OPO
  - ORD
  - ORF
  - ORK
  - ORN
  - ORY
  - OSA
  - OSI
  - OSL
  - OSR
  - OSS
  - OST
  - OSZ
  - OTP
  - OUA
  - OUD
  - OUL
  - OVD
  - PAZ
  - PBC
  - PBI
  - PCL
  - PDL
  - PDS
  - PDV
  - PDX
  - PED
  - PEK
  - PEN
  - PER
  - PEV
  - PEW
  - PFO
  - PGF
  - PGK
  - PHC
  - PHE
  - PHL
  - PHX
  - PIA
  - PIE
  - PIS
  - PIU
  - PKE
  - PKN
  - PKR
  - PKU
  - PKY
  - PLH
  - PLM
  - PLQ
  - PLS
  - PLX
  - PLZ
  - PMC
  - PMI
  - PMK
  - PMO
  - PMR
  - PMV
  - PNH
  - PNK
  - PNS
  - POA
  - POP
  - POR
  - POS
  - POV
  - POZ
  - PPL
  - PPQ
  - PPS
  - PPT
  - PQM
  - PQQ
  - PRG
  - PSA
  - PSP
  - PUJ
  - PUQ
  - PUS
  - PUV
  - PUY
  - PVD
  - PVG
  - PVK
  - PVR
  - PWQ
  - PXO
  - PYE
  - QOW
  - QRO
  - RAK
  - RAP
  - RAR
  - RDU
  - RDZ
  - REC
  - REG
  - REP
  - REX
  - RGI
  - RGN
  - RHO
  - RIC
  - RIX
  - RJB
  - RJH
  - RJK
  - RKV
  - RMA
  - RNE
  - RNJ
  - RNO
  - RNS
  - ROB
  - ROC
  - ROK
  - ROM
  - ROT
  - RSD
  - RST
  - RSU
  - RSW
  - RTA
  - RTM
  - RTS
  - RUH
  - RUK
  - RUR
  - RVN
  - RYK
  - RZE
  - SAL
  - SAN
  - SAT
  - SAV
  - SAW
  - SBF
  - SBN
  - SBW
  - SBZ
  - SCL
  - SCO
  - SCQ
  - SCU
  - SDJ
  - SDK
  - SDQ
  - SEA
  - SEN
  - SFA
  - SFB
  - SFO
  - SGE
  - SGN
  - SHB
  - SHE
  - SHJ
  - SHM
  - SHT
  - SHV
  - SIF
  - SIN
  - SJC
  - SJD
  - SJJ
  - SJU
  - SKG
  - SKH
  - SKP
  - SKT
  - SKZ
  - SLA
  - SLC
  - SLD
  - SLL
  - SLP
  - SLU
  - SMA
  - SMF
  - SNA
  - SNN
  - SNU
  - SNW
  - SOB
  - SOF
  - SOH
  - SOU
  - SPC
  - SPD
  - SPI
  - SPU
  - SQQ
  - SRQ
  - SSA
  - SSH
  - STI
  - STL
  - STN
  - STO
  - STR
  - SUF
  - SUJ
  - SUV
  - SUX
  - SVD
  - SVQ
  - SVU
  - SWA
  - SWF
  - SXB
  - SXF
  - SYD
  - SYO
  - SYR
  - SZF
  - SZG
  - SZX
  - SZY
  - SZZ
  - TAM
  - TAO
  - TAP
  - TAR
  - TAS
  - TAT
  - TBP
  - TDK
  - TER
  - TEU
  - TFN
  - TGD
  - TGG
  - TGZ
  - THL
  - THO
  - TIA
  - TII
  - TIJ
  - TIU
  - TKN
  - TKU
  - TLC
  - TLE
  - TLH
  - TLL
  - TLS
  - TLV
  - TMI
  - TMM
  - TMP
  - TMW
  - TNE
  - TNG
  - TNR
  - TOB
  - TOL
  - TOS
  - TOU
  - TOY
  - TPA
  - TPE
  - TPJ
  - TPQ
  - TRC
  - TRD
  - TRG
  - TRN
  - TRR
  - TRS
  - TRU
  - TSE
  - TSJ
  - TSN
  - TSR
  - TSV
  - TTH
  - TUB
  - TUC
  - TUF
  - TUK
  - TUL
  - TUN
  - TUO
  - TUS
  - TVU
  - TVY
  - TWU
  - TXL
  - TYR
  - TYS
  - TZA
  - TZN
  - TZX
  - UBJ
  - UBP
  - UET
  - UIO
  - UIP
  - UKB
  - UKK
  - UND
  - UPG
  - UPN
  - URA
  - URC
  - URY
  - URZ
  - USK
  - USM
  - USN
  - UTH
  - UVE
  - UVF
  - VAA
  - VAN
  - VAR
  - VBV
  - VCA
  - VCE
  - VCL
  - VCS
  - VCT
  - VDE
  - VDH
  - VER
  - VEY
  - VFA
  - VGO
  - VIC
  - VIE
  - VII
  - VIJ
  - VKG
  - VKO
  - VLC
  - VLN
  - VNO
  - VPS
  - VRA
  - VRN
  - VSA
  - VTE
  - VTF
  - WAG
  - WAW
  - WDH
  - WGA
  - WHK
  - WIC
  - WIL
  - WJU
  - WKJ
  - WLG
  - WMB
  - WNS
  - WRO
  - WSZ
  - WUH
  - WUN
  - XCR
  - XIY
  - XMN
  - XNA
  - XNN
  - XRY
  - XTG
  - YCB
  - YCO
  - YDA
  - YDE
  - YDF
  - YDL
  - YDP
  - YDQ
  - YEG
  - YEI
  - YEN
  - YET
  - YEU
  - YEV
  - YEY
  - YFA
  - YFB
  - YFC
  - YFE
  - YFH
  - YFJ
  - YFO
  - YFR
  - YFS
  - YFX
  - YGA
  - YGB
  - YGH
  - YGJ
  - YGK
  - YGL
  - YGM
  - YGO
  - YGP
  - YGQ
  - YGR
  - YGT
  - YGV
  - YGW
  - YGX
  - YGZ
  - YHA
  - YHB
  - YHD
  - YHE
  - YHF
  - YHG
  - YHI
  - YHK
  - YHM
  - YHN
  - YHO
  - YHP
  - YHR
  - YHS
  - YHT
  - YHU
  - YHY
  - YHZ
  - YIB
  - YIC
  - YIF
  - YIH
  - YIK
  - YIN
  - YIO
  - YIP
  - YIV
  - YIW
  - YJA
  - YJF
  - YJN
  - YJT
  - YKA
  - YKF
  - YKG
  - YKL
  - YKM
  - YKQ
  - YKX
  - YKY
  - YKZ
  - YLA
  - YLB
  - YLC
  - YLD
  - YLJ
  - YLL
  - YLQ
  - YLR
  - YLS
  - YLT
  - YLW
  - YMA
  - YMB
  - YMD
  - YME
  - YMG
  - YMH
  - YMJ
  - YML
  - YMM
  - YMO
  - YMP
  - YMT
  - YMX
  - YNA
  - YNB
  - YNC
  - YND
  - YNE
  - YNG
  - YNJ
  - YNL
  - YNM
  - YNO
  - YNP
  - YNR
  - YNS
  - YNT
  - YNY
  - YNZ
  - YOA
  - YOC
  - YOD
  - YOG
  - YOH
  - YOJ
  - YOK
  - YOL
  - YON
  - YOO
  - YOP
  - YOS
  - YOT
  - YOW
  - YOY
  - YPA
  - YPB
  - YPC
  - YPD
  - YPE
  - YPG
  - YPH
  - YPL
  - YPM
  - YPN
  - YPO
  - YPP
  - YPQ
  - YPR
  - YPS
  - YPT
  - YPW
  - YPX
  - YPY
  - YPZ
  - YQA
  - YQB
  - YQC
  - YQD
  - YQF
  - YQG
  - YQH
  - YQI
  - YQK
  - YQL
  - YQM
  - YQN
  - YQQ
  - YQR
  - YQS
  - YQT
  - YQU
  - YQV
  - YQW
  - YQX
  - YQY
  - YQZ
  - YRA
  - YRB
  - YRC
  - YRD
  - YRF
  - YRG
  - YRI
  - YRJ
  - YRL
  - YRM
  - YRN
  - YRO
  - YRQ
  - YRR
  - YRS
  - YRT
  - YRV
  - YSA
  - YSB
  - YSC
  - YSD
  - YSE
  - YSF
  - YSG
  - YSH
  - YSJ
  - YSK
  - YSL
  - YSM
  - YSN
  - YSO
  - YSP
  - YSQ
  - YSR
  - YSS
  - YST
  - YSU
  - YSX
  - YSY
  - YSZ
  - YTA
  - YTB
  - YTD
  - YTE
  - YTF
  - YTG
  - YTH
  - YTJ
  - YTL
  - YTM
  - YTQ
  - YTR
  - YTS
  - YTT
  - YTU
  - YTX
  - YTZ
  - YUA
  - YUB
  - YUD
  - YUE
  - YUL
  - YUM
  - YUS
  - YUT
  - YUX
  - YUY
  - YVA
  - YVB
  - YVC
  - YVD
  - YVE
  - YVG
  - YVH
  - YVI
  - YVJ
  - YVL
  - YVM
  - YVO
  - YVP
  - YVQ
  - YVR
  - YVS
  - YVT
  - YVV
  - YVZ
  - YWA
  - YWB
  - YWG
  - YWK
  - YWL
  - YWM
  - YWP
  - YWQ
  - YWR
  - YWS
  - YWY
  - YXC
  - YXE
  - YXH
  - YXJ
  - YXK
  - YXL
  - YXN
  - YXP
  - YXQ
  - YXR
  - YXS
  - YXT
  - YXU
  - YXX
  - YXY
  - YXZ
  - YYB
  - YYC
  - YYD
  - YYE
  - YYF
  - YYG
  - YYH
  - YYJ
  - YYL
  - YYM
  - YYN
  - YYQ
  - YYR
  - YYS
  - YYT
  - YYU
  - YYW
  - YYY
  - YYZ
  - YZA
  - YZD
  - YZE
  - YZF
  - YZG
  - YZH
  - YZP
  - YZR
  - YZS
  - YZT
  - YZU
  - YZV
  - YZW
  - YZX
  - YZY
  - YZZ
  - ZAD
  - ZAG
  - ZAJ
  - ZAL
  - ZAM
  - ZCL
  - ZCO
  - ZHA
  - ZIG
  - ZIH
  - ZLO
  - ZMM
  - ZNU
  - ZNZ
  - ZQN
  - ZQW
  - ZRH
  - ZSA
  - ZTH
  - ZUH
  - ZVK
  - ZYL

# Plage de dates à scanner (en jours à partir d'aujourd'hui)
min_days_from_now: 7
max_days_from_now: 120

# Durée du séjour pour les billets aller-retour (en jours)
min_stay_days: 3   # Séjour minimum (3 jours)
max_stay_days: 30  # Séjour maximum (30 jours)

# Optimisations pour accélérer le scan (exhaustivité préservée)
stay_days_step: 1        # Teste TOUTES les durées de séjour (3, 4, 5, 6... jusqu'à 15 jours) - exhaustif
date_step_days: 7        # Teste toutes les semaines (exhaustif, comme avant)
request_delay: 0.3        # Délai entre les requêtes en secondes (0.3 au lieu de 1 seconde) = 3x plus rapide
max_concurrent_requests: 10  # Nombre de requêtes parallèles (10 au lieu de 1) = 10x plus rapide

# Prix maximum pour un deal (en EUR)
max_price: 200

# Seuil de réduction minimum pour considérer un deal (0.5 = 50%)
discount_threshold: 0.5

# Nombre minimum d'observations historiques avant de notifier un deal
min_observations: 10

# Intervalle entre chaque cycle de scan (en secondes)
# 3600 = 1 heure, 7200 = 2 heures, etc.
scan_interval_seconds: 3600

# Chemin vers la base de données SQLite
db_path: flights.db

# Fichier de log
log_file: scanner.log

